[package]
name = "town_simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
derive-getters = "0.2"
derive_more = "0.99"
serde = "1.0"